### PR TITLE
urlSlice can handle urls with both query params and hash strings

### PR DESCRIPTION
**Pull request by jgarciabengochea**
My idea for implementation is on finding a query params identifier we will search from the next index to the end of the string looking for a fragment identifier. If the index of the fragment Identifier is greater than the index of the params Identifier (I realize this is redundant now because we only search the substring after the params identifier, my initial implementation was to check if it was greater than 0 ie. we found it) then we will create a hashStr from the fragment identifier to the end of the string and create a queryStr from the index of the params identifier to the fragment Identifier. If the fragment Identifier is not found after the query params Identifier we set the fragment identifier to be the length of the string and create a substring from that. I have included tests for all of the cases that you showed me in your examples. The last thing I changed is I saw that .substr() has been deprecated in favor of .substring() which did not impact the implementation of the code I inherited. Thank you for allowing me to have a chance at my first open source contribution! Any feedback or review is welcome!

### CODE REVIEW

**Review by amitguptagwl — CHANGES_REQUESTED** [review]
Please do commented changes. In addition, though I'm not sure if a valid fragment string can have '?' but your code may fail if it has. Can you please check?

**Comment by amitguptagwl** [comment]
long paragraph ;) will read in last :)

**Comment by jgarciabengochea** [comment]
@amitguptagwl just for clarification what do you mean when you say commented changes and to assert query str?

**Comment by amitguptagwl** [comment]
I've reviews your changes and commented on 2 places for the change
1. "It seems a duplicate test."
2. "Please assert query str as well"

> Please do commented changes. In addition, though I'm not sure if a valid fragment string can have '?' but your code may fail if it has. Can you please check?

Example: /test/url#fragment?string

**Comment by amitguptagwl** [comment]
@jgarciabengochea were you able to understand my last comment? Let me know if there is any confusion.

**Comment by jgarciabengochea** [comment]
@amitguptagwl Yes, I realized I had read the statement wrong, I understood you wanted me to make the changes you commented on, not make comments with the changes I made, my mistake. I have made the appropriate changes and asserted the test case you proposed.

**Comment by amitguptagwl** [comment]
Great! There is one last issue. '?' and ';' both are query string identifier. Please check the last else if block

**Comment by amitguptagwl** [comment]
@jgarciabengochea I hope you are on it.

**Comment by jgarciabengochea** [comment]
@amitguptagwl Yes! I am on it, sorry for the delay. So the second query string identifier also needs to be able to handle fragments as well?

**Comment by amitguptagwl** [comment]
EVerything would be the same. Only the change is when you're checking for a char to be `?`, you will have to check for both `?` or `;`. And remove last else block.

```js
if ( url[i] === '?' || url[i] === ';') {
//..
}
```

**Comment by jgarciabengochea** [comment]
Ok great, that's what I assumed you meant but wanted to confirm. Submitted the changes.

**Comment by jgarciabengochea** [comment]
@amitguptagwl Thank you so much for guiding me through this process! I appreciate the opportunity it was a great learning experience!

**Pull request merged**
